version: "3"
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT

  # Open Telemetry
  #
  # The Otel Collector and Otel Agent are actually the same thing,
  # the only difference is that the agent is configued to be 'lighter'
  # acting as a proxy that runs alongside the host application, forwarding
  # the data through to the actual collector (external to the application host),
  # which then does most of the heavy lifting
  #
  # An agent would be deployed on the same host
  # The collector would be at a cluster/regional level

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678" # OpenCensus receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - prometheus

  # Agent
  otel-agent:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777" # pprof extension
      - "4317:4317"
      - "8887:8888" # Prometheus metrics exposed by the agent
      - "14268" # Jaeger receiver
      - "55678" # OpenCensus receiver
      - "55679:55679" # zpages extension
      - "13133" # health_check
    depends_on:
      - otel-collector

  # Example OTEL compatible backends

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
